version: '3'
name: 'discord role bot'

services:
  botserver:
    type: node:14

tooling:
  yarn:
    service: botserver
  npm:
    service: botserver
  npx:
    service: botserver
  node:
    service: botserver
