arrowParens: avoid
bracketSpacing: true
endOfLine: lf
importOrder:
  - ^[^\.](.*)
  - ^(.*)
importOrderSeparation: true
printWidth: 80
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: true
